### ISSUE TITLE
I am getting an error when packaging and running as a Jar.

### ISSUE THREAD

**Issue by gbible45** [ascrus/getl#14]
When using Getl, it runs normally when run in IDE (Intellij), but an error occurs when packaged as a jar and run.
How do I solve this problem?

gradle
```
plugins {
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'java'
    id 'idea'
    id 'application'
}

version '0.0.1'

configurations {
    addJars
}

repositories {
    mavenCentral()
}

dependencies {
    api(group: 'net.sourceforge.getl', name: 'getl', version: '4.18.4')
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
}
```

error line code
```
etl.copyRows(mysqlTable('mysql:product'), mysqlTable('mysql:trans_product'))
```

error
```
2023-08-07 10:27:58 [ SEVERE]: Error parse Groovy script
2023-08-07 10:27:58 [ SEVERE]: Can not save dump, required logFileName!
script:
Closure code = { java.sql.Connection connection, groovy.sql.GroovyResultSet inRow, Map outRow -> methodRowCopy(connection, inRow, outRow) }

@groovy.transform.CompileStatic
void methodRowCopy(java.sql.Connection connection, groovy.sql.GroovyResultSet inRow, Map outRow) {
        def _getl_temp_var_1 = inRow.getAt('id')
        if (_getl_temp_var_1 == null) outRow.put('id', null) else {
                outRow.put('id', _getl_temp_var_1)
        }
        def _getl_temp_var_2 = inRow.getAt('name')
        if (_getl_temp_var_2 == null) outRow.put('name', null) else {
                outRow.put('name', _getl_temp_var_2)
        }
        def _getl_temp_var_3 = inRow.getAt('price')
        if (_getl_temp_var_3 == null) outRow.put('price', null) else {
                outRow.put('price', _getl_temp_var_3)
        }
        def _getl_temp_var_4 = inRow.getAt('created')
        if (_getl_temp_var_4 == null) outRow.put('created', null) else {
                _getl_temp_var_4 = (_getl_temp_var_4 as java.time.LocalDateTime).toDate().toTimestamp()
                outRow.put('created', _getl_temp_var_4)
        }
}
return code
vars:
2023-08-07 10:27:58 [ SEVERE]: Error reading dataset "etl_table_from.product": <org.codehaus.groovy.control.MultipleCompilationErrorsException> startup failed:
Script1.groovy: 19: [Static type checking] - Cannot find matching method java.time.LocalDateTime#toDate(). Please check if the declared type is correct and if the method exists.
 @ line 19, column 74.
   ava.time.LocalDateTime).toDate().toTimes
                                 ^
2023-08-07 10:27:58 [ SEVERE]: Can not save dump, required logFileName!
{ Map inRow, Map outRow ->
        method_1(inRow, outRow)
}

@groovy.transform.CompileStatic
void method_1 (Map inRow, Map outRow) {
outRow.put('id', inRow.get('id'))
outRow.put('name', inRow.get('name'))
outRow.put('price', inRow.get('price'))
outRow.put('created', inRow.get('created'))
outRow.put('discount', getl.utils.GenerationUtils.EMPTY_BOOLEAN)

}
2023-08-07 10:27:58 [ SEVERE]: Error copying rows from "etl_table_from.product" to "etl_table_to.trans_product": <org.codehaus.groovy.control.MultipleCompilationErrorsException> startup failed:
Script1.groovy: 19: [Static type checking] - Cannot find matching method java.time.LocalDateTime#toDate(). Please check if the declared type is correct and if the method exists.
 @ line 19, column 74.
   ava.time.LocalDateTime).toDate().toTimes
                                 ^
Exception in thread "main" org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 19: [Static type checking] - Cannot find matching method java.time.LocalDateTime#toDate(). Please check if the declared type is correct and if the method exists.
 @ line 19, column 74.
   ava.time.LocalDateTime).toDate().toTimes
                                 ^

Script1.groovy: 19: [Static type checking] - Cannot find matching method java.lang.Object#toTimestamp(). Please check if the declared type is correct and if the method exists.
 @ line 19, column 22.
                _getl_temp_var_4 = (_getl_temp_var_4 as java.time.LocalDateTime).toDate().toTimestamp()
                        ^

2 errors

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:985)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:672)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:636)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:426)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at getl.utils.GenerationUtils.EvalGroovyScript(GenerationUtils.groovy:1734)
        at getl.utils.GenerationUtils$EvalGroovyScript$1.callStatic(Unknown Source)
        at getl.utils.GenerationUtils.EvalGroovyScript(GenerationUtils.groovy)
        at getl.utils.GenerationUtils$EvalGroovyScript$0.callStatic(Unknown Source)
        at getl.utils.GenerationUtils.EvalGroovyClosure(GenerationUtils.groovy:1679)
        at getl.utils.GenerationUtils$EvalGroovyClosure.callStatic(Unknown Source)
        at getl.utils.GenerationUtils.EvalGroovyClosure(GenerationUtils.groovy)
        at getl.utils.GenerationUtils$EvalGroovyClosure$2.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
        at getl.utils.GenerationUtils.GenerateRowCopy(GenerationUtils.groovy:2070)
        at getl.utils.GenerationUtils.GenerateRowCopy(GenerationUtils.groovy)
        at getl.jdbc.JDBCDriver$_eachRow_closure15.doCall(JDBCDriver.groovy:1918)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at groovy.sql.Sql.eachRow(Sql.java:1221)
        at getl.jdbc.JDBCDriver.eachRow(JDBCDriver.groovy:1954)
        at getl.jdbc.JDBCDriver$eachRow$13.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
        at getl.data.Dataset.eachRow(Dataset.groovy:1181)
        at getl.proc.Flow.copy(Flow.groovy:910)
        at getl.proc.Flow.copy(Flow.groovy)
        at getl.proc.Flow$copy.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at getl.proc.opts.FlowCopySpec.runProcess(FlowCopySpec.groovy:381)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at getl.proc.opts.FlowBaseSpec.doProcess(FlowBaseSpec.groovy:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at getl.proc.opts.FlowCopySpec.copyRow(FlowCopySpec.groovy:375)
        at getl.proc.opts.FlowCopySpec$copyRow.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at getl.lang.opts.EtlSpec.copyRows(EtlSpec.groovy:60)
        at getl.lang.opts.EtlSpec.copyRows(EtlSpec.groovy)
        at getl.lang.opts.EtlSpec$copyRows.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at TableToTable.run(TableToTable.groovy:39)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:470)
        at groovy.lang.GroovyShell$evaluate.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at com.okestro.metronome.getl.launcher.GroovyShellRun.main(GroovyShellRun.groovy:24)
```

**Comment by ascrus** [comment]
Hi. What version of Java is used to run the jar file?

**Comment by ascrus** [comment]
Try version 4.18.5, this bug should be fixed there.

**Comment by gbible45** [comment]
> Hi. What version of Java is used to run the jar file?
The java version used JDK 17.0.8.

> Try version 4.18.5, this bug should be fixed there.
I tried version 4.18.5 and it works fine. Thank you
